# Generated by Django 5.2.12 on 2026-03-12 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KGProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512, verbose_name="图谱名称")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "source_app",
                    models.CharField(
                        choices=[
                            ("paper_lab", "学术研究站"),
                            ("memoryforge", "记忆熔炉"),
                            ("api", "API调用"),
                            ("manual", "手动创建"),
                        ],
                        default="manual",
                        max_length=32,
                    ),
                ),
                (
                    "source_project_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="来源项目ID"
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(default=False, verbose_name="是否共享"),
                ),
                (
                    "node_count",
                    models.IntegerField(default=0, verbose_name="节点数缓存"),
                ),
                ("edge_count", models.IntegerField(default=0, verbose_name="边数缓存")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kg_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "知识图谱项目",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="KGNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        db_index=True, max_length=512, verbose_name="节点标签"
                    ),
                ),
                (
                    "node_type",
                    models.CharField(
                        choices=[
                            ("concept", "概念"),
                            ("entity", "实体"),
                            ("event", "事件"),
                            ("claim", "论断"),
                            ("method", "方法"),
                            ("result", "结论"),
                            ("character", "人物"),
                            ("paper", "论文"),
                            ("place", "地点"),
                            ("term", "术语"),
                            ("memory", "记忆"),
                        ],
                        db_index=True,
                        default="concept",
                        max_length=16,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="描述"),
                ),
                (
                    "aliases",
                    models.JSONField(blank=True, default=list, verbose_name="别名列表"),
                ),
                (
                    "keywords",
                    models.JSONField(blank=True, default=list, verbose_name="关键词"),
                ),
                (
                    "importance",
                    models.FloatField(default=0.5, verbose_name="重要度(PageRank)"),
                ),
                (
                    "visit_count",
                    models.IntegerField(default=0, verbose_name="访问次数"),
                ),
                (
                    "source_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1024,
                        verbose_name="来源引用(file.md:L45-60)",
                    ),
                ),
                (
                    "source_lit_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="来源文献ID"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kg_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nodes",
                        to="knowledge_graph.kgproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识节点",
                "ordering": ["-importance", "label"],
            },
        ),
        migrations.CreateModel(
            name="KGEdge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("supports", "支持"),
                            ("contradicts", "矛盾"),
                            ("causes", "导致"),
                            ("extends", "扩展"),
                            ("related_to", "相关"),
                            ("defines", "定义"),
                            ("exemplifies", "举例"),
                            ("cites", "引用"),
                            ("part_of", "组成"),
                            ("leads_to", "推导"),
                            ("opposes", "对立"),
                            ("has_method", "使用方法"),
                            ("has_result", "得出结论"),
                            ("is_a", "属于"),
                            ("instance_of", "实例化"),
                            ("precedes", "先于"),
                            ("follows", "后于"),
                        ],
                        default="related_to",
                        max_length=16,
                    ),
                ),
                ("weight", models.FloatField(default=1.0, verbose_name="权重")),
                ("confidence", models.FloatField(default=0.8, verbose_name="置信度")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="关系描述"),
                ),
                (
                    "source_citation",
                    models.CharField(
                        blank=True, default="", max_length=1024, verbose_name="来源引用"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="out_edges",
                        to="knowledge_graph.kgnode",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_edges",
                        to="knowledge_graph.kgnode",
                    ),
                ),
                (
                    "kg_project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="edges",
                        to="knowledge_graph.kgproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "知识边",
            },
        ),
        migrations.CreateModel(
            name="KGCallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("extract_text", "文本提取节点"),
                            ("add_node", "添加节点"),
                            ("add_edge", "添加边"),
                            ("query_subgraph", "查询子图"),
                            ("search_nodes", "搜索节点"),
                            ("find_path", "路径搜索"),
                            ("batch_extract", "批量提取"),
                            ("get_context", "获取RAG上下文"),
                            ("compute_rank", "计算节点排名"),
                            ("bfs_traverse", "BFS遍历"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "caller_app",
                    models.CharField(
                        choices=[
                            ("paper_lab", "学术研究站"),
                            ("memoryforge", "记忆熔炉"),
                            ("api", "直接API"),
                            ("manual", "手动操作"),
                            ("system", "系统内部"),
                        ],
                        default="api",
                        max_length=16,
                    ),
                ),
                (
                    "input_length",
                    models.IntegerField(default=0, verbose_name="输入文本长度"),
                ),
                (
                    "nodes_created",
                    models.IntegerField(default=0, verbose_name="新建节点数"),
                ),
                (
                    "edges_created",
                    models.IntegerField(default=0, verbose_name="新建边数"),
                ),
                (
                    "nodes_traversed",
                    models.IntegerField(default=0, verbose_name="遍历节点数"),
                ),
                (
                    "edges_traversed",
                    models.IntegerField(default=0, verbose_name="遍历边数"),
                ),
                (
                    "result_nodes",
                    models.IntegerField(default=0, verbose_name="结果节点数"),
                ),
                (
                    "duration_ms",
                    models.IntegerField(default=0, verbose_name="耗时(ms)"),
                ),
                (
                    "llm_tokens_input",
                    models.IntegerField(default=0, verbose_name="LLM输入Token"),
                ),
                (
                    "llm_tokens_output",
                    models.IntegerField(default=0, verbose_name="LLM输出Token"),
                ),
                (
                    "memory_bytes_estimated",
                    models.IntegerField(default=0, verbose_name="估计内存(bytes)"),
                ),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kg_call_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "kg_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="call_logs",
                        to="knowledge_graph.kgproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "图谱调用日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="kgnode",
            index=models.Index(
                fields=["kg_project", "label"], name="knowledge_g_kg_proj_f457aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kgnode",
            index=models.Index(
                fields=["kg_project", "node_type"],
                name="knowledge_g_kg_proj_56c942_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="kgnode",
            index=models.Index(
                fields=["kg_project", "importance"],
                name="knowledge_g_kg_proj_e5a147_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="kgedge",
            index=models.Index(
                fields=["kg_project", "source", "target"],
                name="knowledge_g_kg_proj_b171ae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="kgedge",
            index=models.Index(
                fields=["kg_project", "relation_type"],
                name="knowledge_g_kg_proj_b00a71_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="kgedge",
            index=models.Index(
                fields=["source", "relation_type"],
                name="knowledge_g_source__7bf38f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="kgedge",
            index=models.Index(
                fields=["target", "relation_type"],
                name="knowledge_g_target__1fbd40_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="kgcalllog",
            index=models.Index(
                fields=["user", "created_at"], name="knowledge_g_user_id_46a2ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kgcalllog",
            index=models.Index(
                fields=["kg_project", "operation"],
                name="knowledge_g_kg_proj_c04214_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="kgcalllog",
            index=models.Index(
                fields=["caller_app", "created_at"],
                name="knowledge_g_caller__f8bcba_idx",
            ),
        ),
    ]
