# Generated by Django 4.2.27 on 2026-03-24 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='puzzle', max_length=50)),
                ('color', models.CharField(default='#c9a86c', max_length=20)),
                ('plugin_type', models.CharField(choices=[('code', 'Code Plugin'), ('nocode', 'No-Code Plugin')], default='nocode', max_length=10)),
                ('html_content', models.TextField(blank=True)),
                ('config', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已上线'), ('rejected', '已拒绝')], default='pending', max_length=10)),
                ('is_public', models.BooleanField(default=True)),
                ('memory_offset', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PluginData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='plugin.plugin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plugin_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('plugin', 'user', 'key')},
            },
        ),
    ]
