# Generated by Django 6.0.3 on 2026-03-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(blank=True, null=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('think', 'Think'), ('action', 'Action'), ('memory', 'Memory'), ('error', 'Error'), ('llm', 'LLM Call')], default='info', max_length=16)),
                ('title', models.CharField(max_length=256)),
                ('content', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=512)),
                ('api_base', models.CharField(default='https://open.bigmodel.cn/api/paas/v4', max_length=512)),
                ('chat_model', models.CharField(default='glm-4.7-flash', max_length=128)),
                ('embedding_model', models.CharField(default='embedding-3', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
