# Generated by Django 5.2.9 on 2026-03-10 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiconfig',
            name='embedding_model',
        ),
    ]
