# Generated by Django 5.2.9 on 2026-03-11 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCRProject',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='项目ID')),
                ('name', models.CharField(max_length=512, verbose_name='文件名')),
                ('total_pages', models.IntegerField(verbose_name='总页数')),
                ('api_key', models.CharField(blank=True, max_length=512, verbose_name='API密钥')),
                ('ocr_prompt', models.TextField(blank=True, verbose_name='OCR提示词')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.CharField(default='uploaded', max_length=20, verbose_name='状态')),
            ],
            options={
                'verbose_name': 'OCR项目',
                'verbose_name_plural': 'OCR项目列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num', models.IntegerField(verbose_name='页码')),
                ('image_path', models.CharField(max_length=1024, verbose_name='图片路径')),
                ('ocr_status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('done', '已完成'), ('error', '错误')], default='pending', max_length=20, verbose_name='OCR状态')),
                ('ocr_result', models.TextField(blank=True, verbose_name='OCR结果')),
                ('error_msg', models.TextField(blank=True, verbose_name='错误信息')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='ocr_studio.ocrproject', verbose_name='项目')),
            ],
            options={
                'verbose_name': 'OCR页面',
                'verbose_name_plural': 'OCR页面列表',
                'ordering': ['page_num'],
                'unique_together': {('project', 'page_num')},
            },
        ),
    ]
