# Generated by Django 4.2.27 on 2026-03-29 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ocr_studio', '0004_ocrpage_model_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrpage',
            name='binary_image',
            field=models.ImageField(blank=True, null=True, upload_to='ocr_pages_binary/%Y/%m/', verbose_name='二值化图片'),
        ),
        migrations.AlterField(
            model_name='ocrpage',
            name='callback_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='回调令牌'),
        ),
        migrations.AlterField(
            model_name='ocrpage',
            name='feedback_text',
            field=models.TextField(blank=True, verbose_name='反馈文本'),
        ),
        migrations.AlterField(
            model_name='ocrpage',
            name='feedback_type',
            field=models.CharField(blank=True, choices=[('like', '点赞'), ('dislike', '点踩')], max_length=20, null=True, verbose_name='反馈类型'),
        ),
        migrations.AlterField(
            model_name='ocrpage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='ocr_pages/%Y/%m/', verbose_name='图片文件'),
        ),
        migrations.AlterField(
            model_name='ocrpage',
            name='image_path',
            field=models.CharField(blank=True, max_length=1024, verbose_name='图片路径'),
        ),
        migrations.AlterField(
            model_name='ocrproject',
            name='processing_mode',
            field=models.CharField(choices=[('api', '直连API模式'), ('worker', 'Worker中继模式')], default='api', max_length=20, verbose_name='处理模式'),
        ),
        migrations.AlterField(
            model_name='ocrproject',
            name='redis_channel',
            field=models.CharField(default='ocr_tasks', help_text='Redis Pub/Sub 频道名称，Worker 订阅此频道接收任务', max_length=100),
        ),
        migrations.AlterField(
            model_name='ocrusagequota',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_quota', to=settings.AUTH_USER_MODEL),
        ),
    ]
