# Generated by Django 6.0.3 on 2026-03-09 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('genre', models.CharField(blank=True, default='', max_length=128)),
                ('synopsis', models.TextField(blank=True, default='')),
                ('style_guide', models.TextField(blank=True, default='')),
                ('world_setting', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=512)),
                ('outline', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('word_count', models.IntegerField(default=0)),
                ('memory_node_id', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('outline', 'Outline'), ('draft', 'Draft'), ('writing', 'Writing'), ('review', 'Review'), ('done', 'Done')], default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novel.project')),
            ],
            options={
                'ordering': ['number'],
                'unique_together': {('project', 'number')},
            },
        ),
    ]
