# Generated by Django 5.2.9 on 2026-03-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_verificationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_cooldown_seconds', models.PositiveIntegerField(default=300, help_text='同一邮箱两次发码的最短间隔，默认 300 秒（5 分钟）', verbose_name='发码冷却（秒）')),
                ('code_expire_minutes', models.PositiveIntegerField(default=30, help_text='验证码从发出到失效的时间，默认 30 分钟', verbose_name='验证码有效期（分钟）')),
                ('code_daily_limit', models.PositiveIntegerField(default=100, help_text='系统每自然日最多发送的验证码总次数，超出后当天无法新注册', verbose_name='全局每日发码上限')),
                ('code_minute_limit', models.PositiveIntegerField(default=5, help_text='全站每分钟最多发送的验证码次数，防止瞬时刷量', verbose_name='全局每分钟发码上限')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
            ],
            options={
                'verbose_name': '系统参数',
                'verbose_name_plural': '系统参数',
            },
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='邮箱'),
        ),
    ]
