# Generated by Django 5.2.9 on 2026-03-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_siteconfig_alter_verificationcode_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_api_key',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='用户自定义API密钥'),
        ),
    ]
