# Generated by Django 4.2.27 on 2026-03-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_is_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='site_favicon',
            field=models.CharField(blank=True, default='', help_text='浏览器标签页图标：填写图片URL（如 /static/favicon.ico）或直接填写 emoji（如 🚀）', max_length=500, verbose_name='网站图标'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_subtitle',
            field=models.CharField(default='多功能应用集成工作台', help_text='显示在登录页标题下方的描述文字', max_length=200, verbose_name='网站副标题'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_title',
            field=models.CharField(default='应用平台', help_text='显示在浏览器标签页、导航栏和登录页的网站名称', max_length=100, verbose_name='网站标题'),
        ),
    ]
