# Generated by Django 5.2.9 on 2026-03-19 15:24

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_siteconfig_branding'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='文件名')),
                ('size', models.PositiveBigIntegerField(verbose_name='文件大小（字节）')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', '图片'), ('doc', '文档'), ('code', '代码'), ('other', '其他')], default='other', max_length=10, verbose_name='文件类型')),
                ('file', models.FileField(upload_to=accounts.models.cloud_upload_path, verbose_name='文件')),
                ('sha256', models.CharField(blank=True, default='', max_length=64, verbose_name='SHA-256')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '云盘文件',
                'verbose_name_plural': '云盘文件',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
