# Generated by Django 5.2.9 on 2026-03-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_mineai_branding_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.FloatField(default=0.0, help_text='1积分=2万输出Token，1积分=5万输入Token', verbose_name='积分'),
        ),
    ]
