# Generated by Django 5.2.9 on 2026-03-30 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_points', models.FloatField(default=10.0, verbose_name='积分数量')),
                ('note', models.CharField(blank=True, default='', help_text='用户填写的赞赏备注，通常是登录邮箱', max_length=200, verbose_name='备注（邮箱）')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已批准'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer_note', models.CharField(blank=True, default='', max_length=200, verbose_name='审核备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '赞赏记录',
                'verbose_name_plural': '赞赏记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
