# Generated by Django 5.2.12 on 2026-03-11 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Literature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1024, verbose_name="文献标题")),
                (
                    "authors",
                    models.CharField(
                        blank=True, default="", max_length=1024, verbose_name="作者"
                    ),
                ),
                (
                    "year",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="年份"
                    ),
                ),
                (
                    "journal",
                    models.CharField(
                        blank=True, default="", max_length=512, verbose_name="期刊/来源"
                    ),
                ),
                (
                    "abstract",
                    models.TextField(blank=True, default="", verbose_name="摘要"),
                ),
                (
                    "keywords_meta",
                    models.JSONField(blank=True, default=list, verbose_name="关键词"),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, default="", verbose_name="全文内容(Markdown)"
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1024,
                        verbose_name="虚拟文件路径",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("ocr", "OCR导入"),
                            ("upload", "MD上传"),
                            ("manual", "手动录入"),
                        ],
                        default="upload",
                        max_length=16,
                    ),
                ),
                (
                    "source_ocr_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=12,
                        verbose_name="来源OCR项目ID",
                    ),
                ),
                ("total_lines", models.IntegerField(default=0, verbose_name="总行数")),
                (
                    "is_indexed",
                    models.BooleanField(default=False, verbose_name="是否已建立索引"),
                ),
                (
                    "is_shared",
                    models.BooleanField(default=False, verbose_name="是否共享"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("zh", "中文"), ("en", "英文"), ("mixed", "混合")],
                        default="zh",
                        max_length=8,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="literatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "文献",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LiteratureChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.IntegerField(verbose_name="块序号")),
                ("line_start", models.IntegerField(verbose_name="起始行号(1-based)")),
                ("line_end", models.IntegerField(verbose_name="结束行号(1-based)")),
                ("content", models.TextField(verbose_name="块内容")),
                (
                    "heading",
                    models.CharField(
                        blank=True, default="", max_length=512, verbose_name="所属标题"
                    ),
                ),
                (
                    "chunk_type",
                    models.CharField(
                        choices=[
                            ("text", "正文"),
                            ("abstract", "摘要"),
                            ("formula", "公式"),
                            ("table", "表格"),
                            ("figure", "图注"),
                            ("reference", "参考文献"),
                        ],
                        default="text",
                        max_length=16,
                    ),
                ),
                (
                    "keywords",
                    models.JSONField(blank=True, default=list, verbose_name="关键词"),
                ),
                ("importance", models.FloatField(default=0.5, verbose_name="重要度")),
                ("access_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "literature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="paper_lab.literature",
                    ),
                ),
            ],
            options={
                "verbose_name": "文献块",
                "ordering": ["literature", "chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="ResearchConversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, default="新对话", max_length=512),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "context_literature",
                    models.ManyToManyField(
                        blank=True, to="paper_lab.literature", verbose_name="上下文文献"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_convs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "研究对话",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "用户"),
                            ("assistant", "AI助手"),
                            ("system", "系统"),
                        ],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField(verbose_name="消息内容")),
                (
                    "citations",
                    models.JSONField(blank=True, default=list, verbose_name="引用列表"),
                ),
                ("token_usage", models.JSONField(blank=True, default=dict)),
                (
                    "retrieval_query",
                    models.TextField(blank=True, default="", verbose_name="检索查询词"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="paper_lab.researchconversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "研究消息",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512, verbose_name="项目标题")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="项目描述"),
                ),
                (
                    "research_questions",
                    models.TextField(blank=True, default="", verbose_name="研究问题"),
                ),
                (
                    "domain",
                    models.CharField(
                        blank=True, default="", max_length=256, verbose_name="研究领域"
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "研究项目",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("annotation", "标注"),
                            ("summary", "摘要笔记"),
                            ("comment", "评论"),
                            ("question", "疑问"),
                            ("insight", "洞见"),
                            ("connection", "关联"),
                        ],
                        default="annotation",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=512)),
                ("content", models.TextField(verbose_name="笔记内容")),
                (
                    "cited_line_start",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="引用起始行"
                    ),
                ),
                (
                    "cited_line_end",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="引用结束行"
                    ),
                ),
                (
                    "cited_text",
                    models.TextField(blank=True, default="", verbose_name="引用原文"),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "literature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="paper_lab.literature",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="paper_lab.researchproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "研究笔记",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResearchIdea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idea_type",
                    models.CharField(
                        choices=[
                            ("gap", "研究空白"),
                            ("contradiction", "文献矛盾"),
                            ("extension", "扩展方向"),
                            ("method", "方法创新"),
                            ("connection", "跨领域连接"),
                            ("hypothesis", "假设"),
                        ],
                        default="gap",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("description", models.TextField(verbose_name="描述")),
                (
                    "evidence_summary",
                    models.TextField(
                        blank=True, default="", verbose_name="证据摘要（含引用）"
                    ),
                ),
                ("confidence", models.FloatField(default=0.5, verbose_name="置信度")),
                ("is_starred", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "evidence_chunks",
                    models.ManyToManyField(
                        blank=True,
                        to="paper_lab.literaturechunk",
                        verbose_name="证据片段",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_ideas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ideas",
                        to="paper_lab.researchproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "研究灵感",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="researchconversation",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conversations",
                to="paper_lab.researchproject",
            ),
        ),
        migrations.AddField(
            model_name="literature",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="literatures",
                to="paper_lab.researchproject",
            ),
        ),
        migrations.CreateModel(
            name="WritingDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                (
                    "content",
                    models.TextField(
                        blank=True, default="", verbose_name="草稿内容(Markdown含引用)"
                    ),
                ),
                (
                    "outline",
                    models.TextField(blank=True, default="", verbose_name="大纲"),
                ),
                ("word_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="paper_lab.researchproject",
                    ),
                ),
                (
                    "referenced_literatures",
                    models.ManyToManyField(blank=True, to="paper_lab.literature"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="writing_drafts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "写作草稿",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="literaturechunk",
            index=models.Index(
                fields=["literature", "line_start", "line_end"],
                name="paper_lab_l_literat_09dbf1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="literaturechunk",
            index=models.Index(
                fields=["literature", "chunk_type"],
                name="paper_lab_l_literat_1d2caa_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="literaturechunk",
            unique_together={("literature", "chunk_index")},
        ),
    ]
