# Generated by Django 6.0.3 on 2026-03-09 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=256)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('description', models.TextField()),
                ('traits', models.JSONField(blank=True, default=list)),
                ('backstory', models.TextField(blank=True, default='')),
                ('current_state', models.TextField(blank=True, default='')),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('project_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CharacterSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_index', models.IntegerField(default=0)),
                ('state', models.TextField()),
                ('traits', models.JSONField(blank=True, default=list)),
                ('beliefs', models.TextField(blank=True, default='')),
                ('goals', models.TextField(blank=True, default='')),
                ('relationships', models.JSONField(blank=True, default=dict)),
                ('change_description', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='memory.character')),
            ],
            options={
                'ordering': ['character', 'chapter_index'],
            },
        ),
        migrations.CreateModel(
            name='MemoryNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(db_index=True)),
                ('level', models.IntegerField(choices=[(0, '世界'), (1, '大陆'), (2, '王国'), (3, '城池'), (4, '街巷')], db_index=True)),
                ('node_type', models.CharField(choices=[('narrative', '叙事'), ('character', '角色'), ('worldbuild', '世界观'), ('plot', '剧情'), ('style', '风格'), ('relation', '关系'), ('foreshadow', '伏笔'), ('setting', '设定')], default='narrative', max_length=16)),
                ('title', models.CharField(max_length=512)),
                ('summary', models.TextField()),
                ('content', models.TextField(blank=True, default='')),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('importance', models.FloatField(default=0.5)),
                ('access_count', models.IntegerField(default=0)),
                ('version', models.IntegerField(default=1)),
                ('story_time', models.CharField(blank=True, default='', max_length=256)),
                ('chapter_index', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='memory.memorynode')),
            ],
            options={
                'ordering': ['level', '-importance', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(db_index=True)),
                ('link_type', models.CharField(choices=[('parent_child', '父子'), ('temporal', '时序'), ('causal', '因果'), ('semantic', '语义'), ('character', '角色'), ('conflict', '冲突'), ('evolution', '演变'), ('foreshadow', '伏笔')], max_length=16)),
                ('weight', models.FloatField(default=1.0)),
                ('description', models.CharField(blank=True, default='', max_length=512)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='memory.memorynode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='memory.memorynode')),
            ],
        ),
        migrations.CreateModel(
            name='MemorySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('summary', models.TextField()),
                ('content', models.TextField(blank=True, default='')),
                ('chapter_index', models.IntegerField(default=0)),
                ('change_reason', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='memory.memorynode')),
            ],
            options={
                'ordering': ['node', 'version'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(db_index=True)),
                ('event_type', models.CharField(choices=[('plot', '剧情'), ('character', '角色变化'), ('worldbuild', '世界观'), ('relation', '关系变化'), ('foreshadow', '伏笔'), ('reveal', '揭示'), ('turning', '转折')], default='plot', max_length=16)),
                ('chapter_index', models.IntegerField(default=0)),
                ('story_time', models.CharField(blank=True, default='', max_length=256)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('characters_involved', models.JSONField(blank=True, default=list)),
                ('impact', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memory_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memory.memorynode')),
            ],
            options={
                'ordering': ['chapter_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CharacterRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(db_index=True)),
                ('relation_type', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('evolution', models.JSONField(blank=True, default=list)),
                ('char_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_a', to='memory.character')),
                ('char_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_b', to='memory.character')),
            ],
            options={
                'unique_together': {('char_a', 'char_b')},
            },
        ),
        migrations.AddIndex(
            model_name='memorynode',
            index=models.Index(fields=['project_id', 'level'], name='memory_memo_project_ec7b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='memorynode',
            index=models.Index(fields=['project_id', 'node_type'], name='memory_memo_project_5b07b9_idx'),
        ),
        migrations.AddIndex(
            model_name='memorynode',
            index=models.Index(fields=['project_id', 'chapter_index'], name='memory_memo_project_3e5811_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='memorylink',
            unique_together={('source', 'target', 'link_type')},
        ),
        migrations.AlterUniqueTogether(
            name='memorysnapshot',
            unique_together={('node', 'version')},
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['project_id', 'chapter_index'], name='memory_time_project_6112f5_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['project_id', 'event_type'], name='memory_time_project_5eee14_idx'),
        ),
    ]
