# Generated by Django 5.2.9 on 2026-03-10 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='memorynode',
            name='embedding',
        ),
    ]
