# Generated by Django 5.2.9 on 2026-03-19 15:33

import django.db.models.deletion
import doc_reader.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_cloudfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='新对话', max_length=255, verbose_name='对话标题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '对话会话',
                'verbose_name_plural': '对话会话列表',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', '助手')], max_length=10, verbose_name='角色')),
                ('selected_texts', models.JSONField(blank=True, default=list, verbose_name='选中的文本片段')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('instruction_type', models.CharField(blank=True, max_length=20, verbose_name='指令类型')),
                ('model', models.CharField(blank=True, max_length=50, verbose_name='使用的模型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='doc_reader.chatsession')),
            ],
            options={
                'verbose_name': '对话消息',
                'verbose_name_plural': '对话消息列表',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentProject',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512, verbose_name='文档名称')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('md', 'Markdown'), ('txt', 'Text')], default='pdf', max_length=10, verbose_name='文件类型')),
                ('total_pages', models.IntegerField(default=0, verbose_name='总页数')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('cached_pages_count', models.IntegerField(default=0, verbose_name='已缓存页数')),
                ('cache_size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='缓存大小(字节)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('cloud_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_projects', to='accounts.cloudfile', verbose_name='云盘文件')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '文档项目',
                'verbose_name_plural': '文档项目列表',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='doc_reader.documentproject'),
        ),
        migrations.CreateModel(
            name='ParseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '进行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('total_pages', models.IntegerField(default=0, verbose_name='总页数')),
                ('completed_pages', models.IntegerField(default=0, verbose_name='已完成页数')),
                ('failed_pages', models.IntegerField(default=0, verbose_name='失败页数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parse_sessions', to='doc_reader.documentproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parse_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '解析会话',
                'verbose_name_plural': '解析会话列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num', models.IntegerField(verbose_name='页码（从1开始）')),
                ('page_image', models.ImageField(blank=True, null=True, upload_to=doc_reader.models.page_upload_path, verbose_name='页面图片')),
                ('page_image_size', models.PositiveBigIntegerField(default=0, verbose_name='图片大小(字节)')),
                ('page_width', models.IntegerField(blank=True, null=True, verbose_name='原始宽度')),
                ('page_height', models.IntegerField(blank=True, null=True, verbose_name='原始高度')),
                ('ocr_status', models.CharField(choices=[('pending', '待解析'), ('processing', '解析中'), ('done', '已完成'), ('error', '错误')], default='pending', max_length=20, verbose_name='解析状态')),
                ('ocr_result_raw', models.TextField(blank=True, verbose_name='OCR原始结果(JSON)')),
                ('ocr_result_md', models.TextField(blank=True, verbose_name='OCR Markdown结果')),
                ('layout_details', models.JSONField(blank=True, default=list, verbose_name='布局详情')),
                ('error_msg', models.TextField(blank=True, verbose_name='错误信息')),
                ('cached_at', models.DateTimeField(auto_now_add=True, verbose_name='缓存时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='doc_reader.documentproject', verbose_name='文档')),
            ],
            options={
                'verbose_name': '文档页面',
                'verbose_name_plural': '文档页面列表',
                'ordering': ['page_num'],
                'unique_together': {('document', 'page_num')},
            },
        ),
    ]
