# Generated by Django 5.2.9 on 2026-03-18 21:56

import django.db.models.deletion
import scan_enhance.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scan_enhance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=512, verbose_name='原始文件名')),
                ('file', models.FileField(max_length=1024, upload_to=scan_enhance.models.upload_to_path, verbose_name='文件')),
                ('file_size', models.PositiveIntegerField(verbose_name='文件大小(bytes)')),
                ('mime_type', models.CharField(max_length=64, verbose_name='MIME 类型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户上传',
                'verbose_name_plural': '用户上传列表',
                'ordering': ['-created_at'],
            },
        ),
    ]
