# Generated by Django 5.2.9 on 2026-03-13 22:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BridgeConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(default='My Computer', max_length=200)),
                ('status', models.CharField(default='offline', max_length=20)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('os_info', models.CharField(blank=True, max_length=200)),
                ('bridge_version', models.CharField(default='1.0', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bridge_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_heartbeat'],
            },
        ),
        migrations.CreateModel(
            name='BridgeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('claude_session_id', models.CharField(blank=True, max_length=200)),
                ('working_dir', models.CharField(max_length=1000)),
                ('initial_prompt', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('permission_mode', models.CharField(choices=[('full_auto', 'Full Auto (dangerously-skip-permissions)'), ('read_only', 'Read Only'), ('default', 'Default (Claude Code standard)')], default='default', max_length=20)),
                ('model_info', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='claude_bridge.bridgeconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BridgeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=20)),
                ('msg_type', models.CharField(max_length=30)),
                ('content', models.JSONField()),
                ('seq', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='claude_bridge.bridgesession')),
            ],
            options={
                'ordering': ['seq', 'timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PendingCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd_type', models.CharField(max_length=30)),
                ('data', models.JSONField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_commands', to='claude_bridge.bridgeconnection')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='claude_bridge.bridgesession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('tool_name', models.CharField(max_length=100)),
                ('tool_input', models.JSONField()),
                ('tool_use_id', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='claude_bridge.bridgesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
