# Generated by Django 4.2.27 on 2026-03-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claude_bridge', '0002_bridge_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridgesession',
            name='status',
            field=models.CharField(default='queued', max_length=20),
        ),
    ]
