# Generated by Django 4.2.27 on 2026-03-19 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banished_purchases', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banished_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '成交记录',
                'verbose_name_plural': '成交记录',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.CharField(max_length=50)),
                ('order_type', models.CharField(choices=[('buy', '买入'), ('sell', '卖出')], max_length=4)),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('filled', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('open', '挂单中'), ('partial', '部分成交'), ('filled', '已成交'), ('cancelled', '已撤单')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banished_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '市场挂单',
                'verbose_name_plural': '市场挂单',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('score', models.IntegerField(default=0)),
                ('population', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('gold', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banished_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '排行榜',
                'verbose_name_plural': '排行榜',
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='BanishedGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.JSONField(blank=True, default=dict)),
                ('year', models.IntegerField(default=1)),
                ('population', models.IntegerField(default=0)),
                ('gold', models.IntegerField(default=0)),
                ('is_ai_active', models.BooleanField(default=False)),
                ('ai_permissions', models.JSONField(blank=True, default=dict)),
                ('ai_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banished_game', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '放逐之城游戏',
                'verbose_name_plural': '放逐之城游戏',
            },
        ),
        migrations.CreateModel(
            name='BanishedSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=100)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('year', models.IntegerField(default=1)),
                ('population', models.IntegerField(default=0)),
                ('gold', models.IntegerField(default=0)),
                ('saved_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banished_saves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '放逐之城存档',
                'verbose_name_plural': '放逐之城存档',
                'unique_together': {('user', 'slot')},
            },
        ),
    ]
