# Generated by Django 5.2.9 on 2026-03-11 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedNovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='书名')),
                ('synopsis', models.TextField(blank=True, verbose_name='简介')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='novel_covers/', verbose_name='封面')),
                ('bg_color', models.CharField(default='#f5f5dc', max_length=50, verbose_name='背景颜色')),
                ('font_family', models.CharField(default='sans-serif', max_length=100, verbose_name='字体')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布')], default='published', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_novels', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '共享小说',
                'verbose_name_plural': '共享小说列表',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='章节号')),
                ('title', models.CharField(max_length=255, verbose_name='章节标题')),
                ('content', models.TextField(verbose_name='正文')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='字数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novel_share.sharednovel', verbose_name='所属小说')),
            ],
            options={
                'verbose_name': '共享章节',
                'verbose_name_plural': '共享章节列表',
                'ordering': ['number'],
                'unique_together': {('novel', 'number')},
            },
        ),
        migrations.CreateModel(
            name='NovelComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_index', models.IntegerField(blank=True, null=True, verbose_name='段落索引')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='评分(1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novel_comments', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='novel_share.sharedchapter', verbose_name='章节')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='novel_share.sharednovel', verbose_name='小说')),
            ],
            options={
                'verbose_name': '小说评论',
                'verbose_name_plural': '小说评论列表',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NovelFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='novel_favorites', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='novel_share.sharednovel', verbose_name='小说')),
            ],
            options={
                'verbose_name': '小说收藏',
                'verbose_name_plural': '小说收藏列表',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'novel')},
            },
        ),
    ]
