# Generated by Django 4.2.27 on 2026-03-28 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomPeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_id', models.CharField(db_index=True, max_length=48, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peers', to='lan_transfer.transferroom')),
            ],
        ),
        migrations.CreateModel(
            name='SignalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_peer_id', models.CharField(db_index=True, max_length=48)),
                ('target_peer_id', models.CharField(blank=True, db_index=True, max_length=48, null=True)),
                ('kind', models.CharField(choices=[('offer', 'offer'), ('answer', 'answer'), ('candidate', 'candidate')], max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='lan_transfer.transferroom')),
            ],
            options={
                'indexes': [models.Index(fields=['room', 'id'], name='lan_transfe_room_id_83ec84_idx'), models.Index(fields=['room', 'target_peer_id', 'id'], name='lan_transfe_room_id_cd5967_idx')],
            },
        ),
    ]
